<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TiempoLimiteCreacion MM</name>
   <tag></tag>
   <elementGuidId>ac372df4-3b6e-49a2-98e4-a2a52177b743</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ucTimeSpanTiempoLimiteEstimadoLlamado_txtMinuto</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'ctl00$cPHPri$ucTimeSpanTiempoLimiteEstimadoLlamado$txtMinuto' and @type = 'text' and @id = 'cPHPri_ucTimeSpanTiempoLimiteEstimadoLlamado_txtMinuto']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_ucTimeSpanTiempoLimiteEstimadoLlamado_txtMinuto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$ucTimeSpanTiempoLimiteEstimadoLlamado$txtMinuto</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ucTimeSpanTiempoLimiteEstimadoLlamado_txtMinuto</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ucTimeSpanTiempoLimiteEstimadoLlamado_txtMinuto&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_ucTimeSpanTiempoLimiteEstimadoLlamado_txtMinuto']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='cPHPri_ucTimeSpanTiempoLimiteEstimadoLlamado_trMinutos']/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr[2]/td[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
