<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_IniciarSesion</name>
   <tag></tag>
   <elementGuidId>84652c9d-40f8-4852-9455-cbde532fb10d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'cPHPri_btnIniciarSesion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_btnIniciarSesion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_btnIniciarSesion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50f13d73-acad-4b61-bfdc-5b36c771f4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4277bd7b-c604-4633-83f3-673769e5f56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$btnIniciarSesion</value>
      <webElementGuid>f4b3cd08-2d4c-4419-9158-266b588e4bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Iniciar sesión</value>
      <webElementGuid>c4b1bf0d-94a0-4b7e-a4d5-49333892916d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$cPHPri$btnIniciarSesion&quot;, &quot;&quot;, true, &quot;Inicio&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>4a16d786-fa57-48f8-a722-0b62b001d58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_btnIniciarSesion</value>
      <webElementGuid>3e2c6fd8-2137-44a4-a69a-8cbba5415a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boton</value>
      <webElementGuid>cd2f39fb-fc08-4223-875e-3194e1ac1384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_btnIniciarSesion&quot;)</value>
      <webElementGuid>6399ac56-2060-443a-bc63-7c3594946090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_btnIniciarSesion']</value>
      <webElementGuid>786908a9-a1cb-4827-99ef-3dbcd6d79013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_UpdatePanelLogin']/table/tbody/tr/td/table/tbody/tr[6]/td/input</value>
      <webElementGuid>79e705cb-a8c4-4007-babf-74a7b64d39cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/input</value>
      <webElementGuid>52325ebb-0805-4fd2-99a1-d91bb7540d38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
