<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Multillamado</name>
   <tag></tag>
   <elementGuidId>2ef4374a-4a8e-41ca-95fd-d9ff05f1a937</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_cbxMultillamado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;cPHPri_upEdicion&quot;]/table/tbody/tr[6]/td[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53d96e21-ffc1-464c-81a4-23df94976d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_cbxMultillamado</value>
      <webElementGuid>92f5ab3e-325c-4235-ac6a-b1612ed5341f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>80f2a053-9a3f-416d-9f45-7e9d96c9dc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$cbxMultillamado</value>
      <webElementGuid>183b4552-8742-4892-9abc-c3d6b2fb4c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_cbxMultillamado&quot;)</value>
      <webElementGuid>ff6e92d0-3044-4d00-a9dc-5d035b46de68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_cbxMultillamado']</value>
      <webElementGuid>864c5755-b4f1-49ed-a3e0-0e72395f2d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_upEdicion']/table/tbody/tr[6]/td[2]/span/input</value>
      <webElementGuid>a8910016-706a-4ed3-87e3-ef98d7f439aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>1a08fec5-3ef3-4c24-b02e-501b58be92ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
