<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gestion</name>
   <tag></tag>
   <elementGuidId>a616b3c2-cf05-425e-be7c-2ae867ff2066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_LoginView1_MenuImagenes1_Panel1']/a[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/img/iconos/Secciones/GestionInformacion.svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7f63cc6a-8aae-4eed-b1a8-12d277b36ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/iconos/Secciones/GestionInformacion.svg</value>
      <webElementGuid>44accd28-4e03-4fd6-8eb5-6db2374268f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_LoginView1_MenuImagenes1_Panel1&quot;)/a[3]/img[1]</value>
      <webElementGuid>2e21865b-0933-4889-bb80-39ad47a26e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_LoginView1_MenuImagenes1_Panel1']/a[3]/img</value>
      <webElementGuid>d771bff0-9fd8-439a-98ad-035677c0f700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>2a2e3770-45ac-4d76-8fad-8b2ef2bb2627</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
