<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Configuracion</name>
   <tag></tag>
   <elementGuidId>c4fcd745-53f6-4ea9-9474-8a444ac4f194</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/img/iconos/Secciones/Configuracion.svg']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;divContenidoPrincipal&quot;]/div[2]/div/div[1]/div[2]/div/a[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>da13185d-0651-4aaa-a335-e05c3afa1e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/iconos/Secciones/Configuracion.svg</value>
      <webElementGuid>f93e0330-3d9b-4b0d-b4d7-02b2ff1ed8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_LoginView1_MenuImagenes1_Panel1&quot;)/a[2]/img[1]</value>
      <webElementGuid>2030286f-bb9e-4835-b080-bafcf2e9e3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>img</name>
      <type>Main</type>
      <value>&lt;img src=&quot;/img/iconos/Secciones/Configuracion.svg&quot;></value>
      <webElementGuid>28653563-a52f-4fbf-8618-6a197f9178f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_LoginView1_MenuImagenes1_Panel1']/a[2]/img</value>
      <webElementGuid>343ed1a5-6e3c-44bf-98f5-aac3551e727a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>3452e805-ab00-4285-b649-2830a7b1da4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
