<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_LimpiarBusqueda</name>
   <tag></tag>
   <elementGuidId>5c51c452-d454-4357-beb1-18659950b50e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_TabContainer1_TabEdicion_ListaRedes_TablaHerramientasRedes_imgLimpiarBusqueda']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer1_TabEdicion_ListaRedes_TablaHerramientasRedes_imgLimpiarBusqueda</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_TabEdicion_ListaRedes_TablaHerramientasRedes_imgLimpiarBusqueda</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Limpiar búsqueda</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/limpiar_20x20.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_TabEdicion_ListaRedes_TablaHerramientasRedes_imgLimpiarBusqueda&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_TabContainer1_TabEdicion_ListaRedes_TablaHerramientasRedes_imgLimpiarBusqueda']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_TabContainer1_TabEdicion_ListaRedes_TablaHerramientasRedes_divBuscar']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@title='Limpiar búsqueda'])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[3]/img</value>
   </webElementXpaths>
</WebElementEntity>
