<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Salir</name>
   <tag></tag>
   <elementGuidId>df08f9ab-2761-42a3-8d55-704deba12e91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '../../../img/Iconos/Terminal/btnCerrar.svg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_lnkSalirTerminal > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_lnkSalirTerminal']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d431f242-7c2e-4e2b-a7ba-7d28d5eed876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Terminal/btnCerrar.svg</value>
      <webElementGuid>3d99d74f-f271-4240-a14c-1675daef868b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_lnkSalirTerminal&quot;)/img[1]</value>
      <webElementGuid>d25fcf85-b397-4bd8-af2d-56ebccc3cbe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_lnkSalirTerminal']/img</value>
      <webElementGuid>63d535ae-70b8-4e7f-b05c-98604f0e1ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a/img</value>
      <webElementGuid>b7801bab-930b-4e0a-8f73-e71fc9acc98b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
