<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Buscar por jerarquia</name>
   <tag></tag>
   <elementGuidId>44a63808-07ea-4808-95dd-72d46f12c28d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.cajaBusquedaTreeview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;selectorCajaJerarquia&quot;]/div[2]/div/div/table/tbody/tr/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e5a405f-09c7-4d68-a162-5bdf15df7539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e33c456-6812-40bd-9e24-aa5f724d40a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cajaBusquedaTreeview</value>
      <webElementGuid>92689953-2b0b-4a97-a919-22671e18f094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_upnlJeraraquiaServiciosArbol&quot;)/div[1]/div[@class=&quot;caja&quot;]/div[@class=&quot;cajaContenido&quot;]/div[1]/div[@class=&quot;treeViewEnvoltura&quot;]/table[1]/tbody[1]/tr[1]/td[2]/input[@class=&quot;cajaBusquedaTreeview&quot;]</value>
      <webElementGuid>7a3f1ed6-3175-4d1f-85f5-5626a5b4c7af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>fe256da9-0b3f-470a-8a1d-2c51474c35e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_upnlJeraraquiaServiciosArbol']/div/div/div[2]/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>a7abefb9-fd44-4928-aa37-c58d52c78571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>7668aec1-ef6a-4645-b08c-82a5899a64bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
