<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nuevo</name>
   <tag></tag>
   <elementGuidId>377aa2fb-4b2e-4a8d-9049-3c5f69cd0edb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_MenuEdicion1_imgNuevo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_MenuEdicion1_imgNuevo</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'cPHPri_MenuEdicion1_imgNuevo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cb8acd94-2423-4e03-9257-c9837ed88377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_MenuEdicion1_imgNuevo</value>
      <webElementGuid>606bd58e-5763-4b9a-973a-967ad8ee1b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../img/Iconos/Edicion/Nuevo2.svg</value>
      <webElementGuid>7fb3d975-4efc-4a97-96bf-a5de318ebc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_MenuEdicion1_imgNuevo&quot;)</value>
      <webElementGuid>feb1c948-8847-42e5-91ba-dd3718a9b479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_MenuEdicion1_imgNuevo']</value>
      <webElementGuid>83c4209f-2c63-4e2c-8198-885c55fb1cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_MenuEdicion1_lkbNuevo']/img</value>
      <webElementGuid>ed6e5e32-ebc1-42ea-94f5-63d860ecbd15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>b04d29cd-77d2-4d1a-923c-6bb9ca084757</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
