<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Seleccionar</name>
   <tag></tag>
   <elementGuidId>68091af3-0351-4a09-845c-b70966e63db3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_Grupos1_GridView > tbody > tr > td.tablaBtnSeleccionar > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;cPHPri_Grupos1_GridView&quot;]/tbody/tr[1]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>56bb55a9-53f0-4d1c-bfca-9a2c1a96be2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$cPHPri$Grupos1$GridView','Select$0')</value>
      <webElementGuid>b0523314-ac4b-42aa-907c-5562b34a9629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccionar</value>
      <webElementGuid>d4a7d026-d25c-4ec0-9685-20b99d2c63df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Grupos1_GridView&quot;)/tbody[1]/tr[1]/td[@class=&quot;tablaBtnSeleccionar&quot;]/a[1]</value>
      <webElementGuid>d7999b65-04cb-4caf-80d1-a8d62a2c31f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_Grupos1_GridView']/tbody/tr/td/a</value>
      <webElementGuid>bbdea6be-4e9d-4bc9-b69c-4f7fc3664075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Seleccionar')])[2]</value>
      <webElementGuid>524520b7-e87c-441f-b30b-46dc7e699707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multillamado'])[1]/following::a[1]</value>
      <webElementGuid>1bc56405-7044-4928-8d5c-7e4079abbbf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terminales'])[4]/following::a[1]</value>
      <webElementGuid>ba62638b-3042-40b1-aa8c-9dc4c403604d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinica Marly - Grupo A'])[2]/preceding::a[1]</value>
      <webElementGuid>edf4f764-920b-4782-8252-cd99de9b1745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinica Marly - Grupo A'])[3]/preceding::a[1]</value>
      <webElementGuid>33c9bd41-096d-4aa2-a3e4-ece74c463595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$cPHPri$Grupos1$GridView','Select$0')&quot;)]</value>
      <webElementGuid>9c5f0a7e-d018-4eeb-bb38-1490dd32cf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/table/tbody/tr/td/a</value>
      <webElementGuid>dce7755f-4ca1-44d5-b7de-195a9fe421c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
